language: python
python:
  - "3.5"
before_install:
  - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in spokehub_rsa.enc -out spokehub_rsa -d
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install packaging
script:
  - flake8 spokehub
  - python manage.py check
  - python manage.py test
  - coverage run --source=spokehub manage.py test spokehub
after_success:
  - coveralls
  - chmod 600 spokehub_rsa
  - ssh-add spokehub_rsa
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && fab deploy -i spokehub_rsa
