# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_auto_20160316_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_email',
            field=models.BooleanField(default=False, verbose_name='Allow Notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='covers', verbose_name='Your background image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='open', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
    ]
