# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 21:21
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import spokehub.profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_auto_20170930_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mugshot',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=spokehub.profile.models.upload_to_mugshot, verbose_name='mugshot'),
        ),
    ]
