# flake8: noqa
# Generated by Django 2.0.3 on 2018-08-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_userenasignup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_profile', 'Can view profile'),)},
        ),
    ]
