# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 12:19
from __future__ import unicode_literals
from django.db import migrations


def twitter_images_to_https(apps, schema_editor):
    NowPost = apps.get_model("main", "NowPost")
    for np in NowPost.objects.filter(service="twitter"):
        if np.image_url.startswith("http://pbs.twimg.com/"):
            np.image_url = np.image_url.replace('http://', 'https://')
            np.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0015_auto_20160611_1216'),
    ]

    operations = [
        migrations.RunPython(twitter_images_to_https)
    ]
