# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160513_1637'),
        ('main', '0016_auto_20160611_1219'),
    ]

    operations = [
    ]
