# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='rhash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='rhash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
