# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20160627_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='extension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='extension',
            field=models.TextField(blank=True, null=True),
        ),
    ]
