# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20160627_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='image',
        ),
    ]
