# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20160627_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowpost',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nowpost',
            name='original',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nowpost',
            name='screen_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nowpost',
            name='service',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nowpost',
            name='service_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nowpost',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nowpost',
            name='video_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reply',
            name='vimeo_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reply',
            name='youtube_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
