# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.9.8 on 2016-10-20 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=b'')),
                ('slug', models.SlugField()),
                ('subhead', models.TextField(blank=True, default=b'')),
                ('date', models.TextField(blank=True, default=b'')),
                ('description', models.TextField(blank=True, default=b'')),
                ('published', models.BooleanField(default=False)),
                ('thumb_hash', models.TextField(blank=True, null=True)),
                ('thumb_extension', models.TextField(blank=True, null=True)),
                ('cardinality', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-cardinality'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(blank=True, default=b'')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.TextField(blank=True, null=True)),
                ('image_extension', models.TextField(blank=True, null=True)),
                ('youtube_id', models.TextField(blank=True, default=b'')),
                ('vimeo_id', models.TextField(blank=True, default=b'')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Project')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='projectmedia',
            order_with_respect_to='project',
        ),
        migrations.AlterOrderWithRespectTo(
            name='projectcontributor',
            order_with_respect_to='project',
        ),
    ]
