# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=b'', help_text=b'<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown</a> and simple HTML may be used here.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text=b'The slug is the bit that goes in the URL. So, <tt>https://spokehub.org/work/<b>this-is-the-slug</b>/</tt>. Keep it short, lowercase, no spaces or punctuation other than dashes, and slugs must all be unique.'),
        ),
    ]
