# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20170512_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', help_text='<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown</a> and simple HTML may be used here.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='The slug is the bit that goes in the URL. So, <tt>https://spokehub.org/work/<b>this-is-the-slug</b>/</tt>. Keep it short, lowercase, no spaces or punctuation other than dashes, and slugs must all be unique.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subhead',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectcontributor',
            name='fullname',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='vimeo_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='youtube_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
